title: Block image
context:
  alt: The chemex
  src: https://images.contentful.com/fo9twyrwpveg/5nCI6r6Z68yoq2WocomYoS/99f9985edfd1073b3936435835d6e5a1/_DSC0082.jpg
  caption: The chemex coffee maker
